targets:
  $default:
    builders:
      drift_dev:
        options:
          # Generate compact code
          compact_query_methods: true
          # Use data classes instead of moor classes
          use_data_class_name_for_companions: true
          # Generate useful methods
          generate_connect_constructor: true
          # Apply specific options to individual tables
          apply_converters_on_variables: true
          # Generate null-aware code
          generate_values_in_copy_with: true
          # Scoped dart analysis
          scoped_dart_components: true
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      riverpod_generator:
        options:
          # Provider naming
          provider_name_prefix: ""
          provider_name_suffix: "Provider"