name: inventory_management
description: "Multi-tenant SaaS inventory management system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.2.0
  
  # Navigation
  go_router: ^16.0.0
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  cloud_functions: ^6.0.0
  firebase_messaging: ^16.0.0
  
  # Local Database
  sqflite: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.3
  
  # UI/UX
  flutter_native_splash: ^2.3.0
  introduction_screen: ^3.1.0
  adaptive_theme: ^3.5.0
  
  # Forms & Validation
  reactive_forms: ^18.1.1
  
  # Utilities
  dio: ^5.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  collection: ^1.18.0
  equatable: ^2.0.5
  
  # Localization
  intl: ^0.20.0
  
  # Image & File
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Barcode
  # mobile_scanner: ^7.0.1  # Disabled for web build compatibility
  qr_flutter: ^4.1.0
  
  # Security
  flutter_secure_storage: ^10.0.0-beta.4
  crypto: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.0
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Connectivity
  connectivity_plus: ^6.1.4
  
  # URL Launcher
  url_launcher: ^6.2.0
  
  # Payments
  # Payment Processing
  flutter_stripe: ^11.3.0
  
  # Charts & Analytics
  fl_chart: ^1.0.0
  
  # PDF Generation
  pdf: ^3.10.0
  printing: ^5.11.0
  
  # Excel Export
  excel: ^4.0.0
  
  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  
  # Loading & Shimmer
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  
  # Dialogs & Toasts
  awesome_dialog: ^3.2.0
  fluttertoast: ^8.2.4
  
  # Date & Time
  syncfusion_flutter_datepicker: ^30.1.38
  
  # Logging
  logger: ^2.0.0
  sqflite_common_ffi_web: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.26.0
  freezed: ^2.4.1
  json_serializable: ^6.9.0
  # riverpod_generator: ^2.3.10
  analyzer: ^7.7.1
  # custom_lint: ^0.5.0
  # riverpod_lint: ^2.3.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  
  # Assets will be added here
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts will be added here
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#2196F3"
  web: true
  android: true
  ios: true